version: '3.8'

services:
  stdio-context7-mcp:
    build:
      context: .
      dockerfile: Dockerfile.improved
    image: stdio-context7-mcp:latest
    container_name: stdio-context7-mcp
    environment:
      - NODE_ENV=production
      - MCP_SERVER_NAME=stdio-context7
      - MCP_SERVER_VERSION=1.0.0
      - CONTEXT7_API_KEY=${CONTEXT7_API_KEY:-}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    stdin_open: true
    tty: true
    # Security hardening
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    # Health check
    healthcheck:
      test: ["CMD", "sh", "-c", "echo '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"ping\",\"params\":{}}' | timeout 5 node dist/server.js --transport stdio > /dev/null"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    # Restart policy
    restart: unless-stopped
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Test service for MCP protocol testing
  mcp-test:
    image: stdio-context7-mcp:latest
    container_name: stdio-context7-test
    environment:
      - NODE_ENV=production
      - MCP_SERVER_NAME=stdio-context7
    stdin_open: true
    tty: true
    profiles:
      - test
    command: >
      sh -c "
        echo 'Testing MCP Protocol...' &&
        echo '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"initialize\",\"params\":{\"protocolVersion\":\"2024-11-05\",\"capabilities\":{\"roots\":{\"listChanged\":true},\"sampling\":{}},\"clientInfo\":{\"name\":\"test-client\",\"version\":\"1.0.0\"}}}' | 
        node dist/server.js --transport stdio
      "
